[package]
name = "raqote_scaling_issue"
version = "0.1.0"
authors = ["Kamil Tomšík <info@tomsik.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raqote = { version = "0.7.10", default-features = false }

